<a href="https://colab.research.google.com/github/AnndyLibeMoore/Python_My_Learn/blob/main/1_Iniciando_Python_Numpy_inicial_Data_S.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color=green> PYTHON PARA DATA SCIENCE - NUMPY
---

# <font color=green> 1. INTRODUCCIÓN A PYTHON
---

# 1.1 Introducción

> Python es un lenguaje de programación de alto nivel con soporte a múltiples paradigmas de programación. Es un proyecto *open source* y desde su surgimiento, en 1991, viene convirtiéndose en uno de los lenguajes de programación interpretados más populares.
>
> En los últimos años Python desarrolló una comunidad activa de procesamiento científico y análisis de datos y viene destacándose como uno de los lenguajes más relevantes cuando el asunto es ciencia de datos y machine learning, tanto en el entorno acadêmico como también en el entorno laboral.

# 1.2 Instalación y entorno de trabajo

### Instalación Local

### https://www.python.org/downloads/
### o
### https://www.anaconda.com/distribution/

### Google Colaboratory

### https://colab.research.google.com

### Verificando versión

In [ ]:
!python -V

Python 3.10.12


# 1.3 Trabajando con Numpy

In [ ]:
import numpy as np


In [ ]:
#importamos el primer archivo en este caso sera txt
#indicamos el tipo de dato q vamos a subir con el dtype
#creamos una variable e importamos el archivo alli.
#indicamos incluso el tipo de dato q contiene el archivo
km = np.loadtxt('carros-km.txt', dtype = int)

In [ ]:
#visualizamos
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

In [ ]:
#cargamos el archivo de años

años = np.loadtxt('carros-años.txt', dtype = int)

In [ ]:
años

array([2003, 1991, 1990, 2020, 2006, 2012, 2020, 2009, 2010, 2011, 2002,
       2007, 2001, 2020, 2009, 2016, 2012, 2020, 2016, 2017, 2002, 2020,
       1994, 1991, 2020, 2020, 2016, 2020, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2020, 2020, 2009, 2020, 2013, 2003, 2020, 2002,
       2020, 2002, 2004, 2001, 2020, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2020, 2020, 2020, 2020, 2020, 2017, 2011, 2001, 1996,
       2020, 1994, 2020, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2020, 2020, 1999, 2007, 1993, 1995, 2020, 2020, 2016, 2011,
       2020, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2020, 2006, 2001, 2020, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2020, 2017, 2020, 2020, 2006, 2015, 2007,
       2005, 2017, 1998, 2020, 1999, 2020, 2009, 2003, 1994, 2020, 1994,
       2020, 2015, 1996, 1997, 1993, 2020, 1992, 1995, 2020, 1990, 2020,
       2020, 1991, 1990, 2012, 2007, 2013, 2000, 20

### Obtener el promedio de kilometros recorridos por año

In [ ]:
"""
la formula seria el
km promedio = total km recorridos / años que el vehiculo ha recorrido
para obtner el total de años recorridos debemos
restar: año actual - año de fabricacion

la formula quedria asi:

km promedio= total km / (año actual - Año fabricación)

"""

'\nla formula seria el\nkm promedio = total km recorridos / años que el vehiculo ha recorrido\npara obtner el total de años recorridos debemos\nrestar: año actual - año de fabricacion\n\nla formula quedria asi:\n\nkm promedio= total km / (año actual - Año fabricación)\n\n'

In [ ]:
"""
crearemos la variable que guardara el resultado, a esta
le indicamos la formula sera km_promedio
km q es la variable q tien os datos de km /
el 2020 q es el año "actual" - años que es la
variable que tiene los años
"""

'\ncrearemos la variable que guardara el resultado, a esta\nle indicamos la formula sera km_promedio\nkm q es la variable q tien os datos de km /\nel 2020 q es el año "actual" - años que es la\nvariable que tiene los años\n'

In [ ]:
km_promedio = km /  (2020 - años)

#aqui nos dice q hay un valor invalido porque hay
#algunos carros fabricados en 2020 asi q el resultados de
#la formula sera 0 y por esto indica q es invalido

<ipython-input-9-604be348fb12>:1: RuntimeWarning: invalid value encountered in divide
  km_promedio = km /  (2020 - años)


In [ ]:
km_promedio

#aqui los valores invalidos los muestra como nan o nulos

array([2.61235294e+03, 1.96965517e+02, 1.23743333e+03,            nan,
       1.83978571e+03, 1.34100000e+03,            nan, 7.05445455e+03,
       9.91970000e+03, 4.21977778e+03, 7.14388889e+02, 6.19384615e+02,
       4.72489474e+03,            nan, 3.76881818e+03, 2.89017500e+04,
       5.80612500e+03,            nan, 9.27150000e+03, 5.05766667e+03,
       5.62183333e+03,            nan, 3.77226923e+03, 3.55031034e+03,
                  nan,            nan, 1.44875000e+03,            nan,
       3.26933333e+03, 3.25451724e+03, 1.31143478e+03, 2.13328000e+03,
       8.86000000e+03, 1.16579310e+03, 1.51140000e+04, 1.75900000e+03,
                  nan,            nan, 5.02363636e+02,            nan,
       1.33450000e+04, 2.39776471e+03,            nan, 4.79455556e+03,
                  nan, 5.41944444e+02, 4.37156250e+03, 1.26052632e+02,
                  nan, 4.72641176e+03, 7.77763636e+03, 3.60685714e+03,
       3.38580000e+03, 6.71050000e+03, 3.53450000e+03, 3.11565385e+03,
      

In [ ]:
type(km_promedio)

#aqui vemos q el tipo de dato de la variable q
#creamos es array numpy

numpy.ndarray

# <font color=green> 2. CARACTERÍSTICAS BÁSICAS DEL LENGUAJE
---

# 2.1 Operaciones matemáticas

### Operadores aritméticos: $+$, $-$, $*$, $/$, $**$, $\%$, $//$

### Suma ($+$)

In [ ]:
2 + 2

4

### Resta ($-$)

In [ ]:
2-2

0

### Multiplicación ($*$)

In [ ]:
2 * 3

6

### División ($/$) y ($//$)
La operación división siempre devuelve un número con punto decimal

In [ ]:
10 / 3

3.3333333333333335

In [ ]:
10 // 3

#este operador retorna solo la parte entera de la división

3

### Exponenciación ($**$)

In [ ]:
2 ** 3


8

### Resto de la división ($\%$)

In [ ]:
10 % 3

1

In [ ]:
10 % 2

0

### Expresiones matemáticas

In [ ]:
"""
la expresion matematica son una serie de nuemeros separada por
operadores donde se resuelve ejecutando los operadores
iniciando con los de mayor prioridad
"""

'\nla expresion matematica son una serie de nuemeros separada por\noperadores donde se resuelve ejecutando los operadores\niniciando con los de mayor prioridad\n'

In [ ]:
5 * 2 + 3 * 2

#aqui el de mayor importancia es la multiplicación

16

In [ ]:
(5 * 2) + (3 * 2)

#el paraentesis es mayor q la multiplicación


16

In [ ]:
5 * (2 + 3) * 2

#aqui encapsulamos la suma y el resultado cambia

50

### La variable _

En el modo interactivo, el último resultado impreso en pantalla es atribuído a la variable _

In [ ]:
#operador underscore ó subguión
#almacena el ultimo resultado q se ejecutó
_

50

In [ ]:
5 * 2

10

In [ ]:
_

10

In [ ]:
#este operador se puede combinar con una operación
_ + 3 * 2

16

In [ ]:
_ / 2

8.0

# 2.2 Variables

### Nombres de variables

- Nombres de variables pueden comenzar con letras (a - z, A - Z) o con el símbolo *underscore* (_):

    > Altura
    >
    > _peso
    
- El resto del nombre puede contener letras, números o el símbolo "_":

    > nombre_de_variable
    >
    > _valor
    >
    > dia_28_11_
    

- Los nombres son *case sensitive*:

    > Nombre_De_Variable ≠ nombre_de_variable ≠ NOMBRE_DE_VARIABLE
    
### <font color=red>Observaciones:
- Existen algumas palabras reservadas del lenguaje que no pueden ser utilizadas como nombres de variables:

| |Lista de palabras <br>reservadas en Python| |
|:-------------:|:------------:|:-------------:|
| and           | as           | not           |
| assert        | finally      | or            |
| break         | for          | pass          |
| class         | from         | nonlocal      |
| continue      | global       | raise         |
| def           | if           | return        |
| del           | import       | try           |
| elif          | in           | while         |
| else          | is           | with          |
| except        | lambda       | yield         |
| False         | True         | None          |

### Declaración de variables

### Operadores de asignación: $=$, $+=$, $-=$, $*=$, $/=$, $**=$, $\%=$, $//=$

In [ ]:
"""
crearemos variables con valor fijo y las usaremos
"""

'\ncrearemos variables con valor fijo y las usaremos\n'

In [ ]:
año_actual = 2020
año_fabricacion = 2003
km_total = 44410.0

In [ ]:
año_actual

2020

In [ ]:
año_fabricacion

2003

In [ ]:
km_total

44410.0

# $$km_{promedio} = \frac {km_{total}}{(Año_{actual} - Año_{fabricación})}$$

### Operaciones con variables

In [ ]:
#con las variables vamos a hacer la operación

In [ ]:
km_total / (año_actual - año_fabricacion)

2612.3529411764707

In [ ]:
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

#asignamos el resultado a otra variable a km_promedio

2612.3529411764707

In [ ]:
año_actual = 2020
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)
km_promedio

2612.3529411764707

In [ ]:
año_actual = 2020
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)

#aqui ya tenemos el km promedio q recorre el carro del
##ejemplo pero ahora quiero saber cuánto habra recorrido
#hasta el 2021
#teniendo en cuenta q mi año actual es 2020
# asi que reescribire la variable km_total
# y le aplicare la siguiente operación
# a km_total que tiene el km total recorrido del carro
#le sumare el km_promedio que recorre por año el carro
km_total = km_total + km_promedio
km_total



47022.35294117647

en la celda anterior obtuve el promedio de km que recorrera el carro en el 2021, tomando en cuenta que el dato que use es que actualmente estoy en el 2020, obtuve el promedio de lo q recorre el auto por año, y obtuve el total de km q habia recorrido hasta el 2020, con esos datos pude obtener la previsión de cuántos km recorreria en el 2021 (año siguiente para el ejemplo) sumando el total de km hasta el 2020 y el promedio q recorre por año. En la siguiente celda obtendre lo mismo pero resumiendo la utima operación con +=


In [ ]:
año_actual = 2020
año_fabricacion = 2003
km_total = 44410.0
km_promedio = km_total / (año_actual - año_fabricacion)

km_total +=  km_promedio
km_total

47022.35294117647

### Conclusión:
```
"valor = valor + 1" es equivalente a "valor += 1"
```

aqui estamos indicando q el valor ó la variable a la izquierda es igual a la propia variable mas el valor indicado a la derecha

### Declaración múltiple

In [ ]:
""""
aqui declarare las tres variables y sus valores en la misma
linea de código solo separada por comas

"""

'"\naqui declarare las tres variables y sus valores en la misma\nlinea de código solo separada por comas\n\n'

In [ ]:
año_actual, año_fabricacion, km_total = 2020, 2003, 44410.0


In [ ]:
año_actual

2020

In [ ]:
año_fabricacion

2003

In [ ]:
km_total

44410.0

# 2.3 Tipos de datos

Los tipos de datos especifican como números y caracteres estarán guardados y manipulados dentro de un programa. Los tipos de datos básicos en Python son:

1. **Números**
    1. ***int*** - Enteros
    - ***float*** - Decimales
- **Booleanos** - Contiene valores True o False. Esencial cuando comenzamos a trabajar con declaraciones condicionales
- ***Strings*** - Secuencia de uno o más caracteres que puede incluir letras, números y otros tipos de caracteres. Representa un texto.
- **None** - Representa la ausencia de valor

### Números

In [ ]:
año_actual = 2020


In [ ]:
año_actual

2020

In [ ]:
type(año_actual)

int

In [ ]:
año_fabricacion = 2013

In [ ]:
type (año_fabricacion)

int

In [ ]:
km_total = 44410.0

In [ ]:
type (km_total)

float

### Booleanos

In [ ]:
zero_km = True

In [ ]:
type (zero_km)

bool

In [ ]:
zero_km = False

In [ ]:
type(zero_km)

bool

### Strings

In [ ]:
nombre = 'Jetta Variant'
nombre

'Jetta Variant'

In [ ]:
#con comillas dobles
nombre = "Jetta Variant"
nombre

'Jetta Variant'

In [ ]:
#y si tengo comillas dentro del texto
nombre = 'Jetta "Variant"'
nombre

'Jetta "Variant"'

In [ ]:

nombre = "'Jetta Variant'"
nombre

"'Jetta Variant'"

In [ ]:
#un string con varias lineas
carro = '''
  Nombre
  Edad
  Nota
'''

In [ ]:
carro

'\n  Nombre\n  Edad\n  Nota\n'

In [ ]:
type(carro)

str

### None

In [ ]:
#variable nula
kilometraje = None
kilometraje

In [ ]:
type(kilometraje)

NoneType

# 2.4 Conversión de tipos

In [ ]:
"""
convertiremos un tipo de variable a otro tipo, estos es necesario
porq la mayoria de veces tendremos datos str pero necesitaremos
camboiralos a numeros para poder hacer operaciones
"""

'\nconvertiremos un tipo de variable a otro tipo, estos es necesario\nporq la mayoria de veces tendremos datos str pero necesitaremos\ncamboiralos a numeros para poder hacer operaciones\n'

In [ ]:
a = 10
b = 20
c = 'Python es '
d = 'genial'

In [ ]:
type(a)

int

In [ ]:
type(b)

int

In [ ]:
type(c)

str

In [ ]:
type(d)

str

In [ ]:
a + b

30

In [ ]:
c + d

'Python es genial'

In [ ]:
#c + a

#esta operación dará error
#para hacer una operacion ambas variables deben ser del msimo tipo

### Conversiones de tipo

Funciones int(), float(), str()

In [ ]:
#cada funcion anteriormente mencionada convierte el valor
#q se le otorgue segun lo q es, osea si es int convertira
#el valor q se le de a un int y asi

"""
hay q tener en cuenta q no siempre sera posible por jemplo
la variable c no se puede convertir a int
mientras que la variable a y b sí pueden ser convertidas a
texto
"""

'\nhay q tener en cuenta q no siempre sera posible por jemplo\nla variable c no se puede convertir a int\nmientras que la variable a y b sí pueden ser convertidas a\ntexto\n'

In [ ]:
str(a)

'10'

In [ ]:
type(str(a))

str

In [ ]:
c + str(a)

'Python es 10'

In [ ]:
float(a)

10.0

In [ ]:
var = 3.141592

In [ ]:
int(var)

3

In [ ]:
var = 3.99

In [ ]:
int(var)

3

# 2.5 Indentación, comentarios y formatación de *strings*

### Indentación

En el lenguaje Python los programas son estructurados por medio de indentación. En cualquier lenguaje de programación la práctica de colocar indentación es bastante útil, facilitando la lectura y también el mantenimiento del código. En Python la indentación no es solamente una cuestión de organización y estilo, sino que es un requisito del lenguaje.

In [ ]:
"""
en el siguiente ejemplo el bucle if  else nos muestra
la importacia de la indentación.
"""

'\nen el siguiente ejemplo el bucle if  else nos muestra\nla importacia de la indentación.\n'

In [ ]:
año_actual = 2020
año_fabricacion = 2020

if (año_actual == año_fabricacion):
    print('Verdadero')
else:
    print('Falso')

Verdadero


In [ ]:
#si quetamos la indentación dara un error diciendo
#que esta esprando la indentación

In [ ]:
año_actual = 2020
año_fabricacion = 2021

if (año_actual == año_fabricacion):
    print('Verdadero')
else:
    print('Falso')

Falso


### Comentarios

Comentarios son extremamente importantes en un programa. Consiste en un texto que describe lo que el programa o una parte específica del programa está haciendo. Los comentarios son ignorados por el interpretador Python.

Podemos tener comentarios de una única linea o de múltiples líneas.

In [ ]:
# Esto es un comentario
año_actual = 2020
año_actual

2020

In [ ]:
# Esto
# es un
# comentario
año_actual = 2020
año_actual

2020

In [ ]:
'''Esto es un
comentario'''
año_actual = 2020
año_actual

2020

In [ ]:
# Definiendo variables
año_actual = 2020
año_fabricacion = 2020

'''
Estructura condicional que vamos
a aprender la próxima clase
'''
if (año_actual == año_fabricacion):   # Probando si la condición es verdadera
    print('Verdadero')
else:                               # Probando si la condición es falsa
    print('Falso')

Verdadero


### Formatación de *strings*

## *str.format()*

https://docs.python.org/3.6/library/stdtypes.html#str.format

In [ ]:
''' formactacion de strings, me sirve para mostrar
los resultados, esto lo usamos cuando debemos mostrarlo
al usuario final
veremos ejemplos de hacerlo

'''

' formactacion de strings, me sirve para mostrar\nlos resultados, esto lo usamos cuando debemos mostrarlo\nal usuario final\nveremos ejemplos de hacerlo\n\n'

In [ ]:
print('Hola, {}')

Hola, {}


In [ ]:
''' el texto que esta dentro del print tambien es un objeto
de python y tiene metodos, como el format. El format
puedo pasarle parlabras com parametros, solo debo ponelas
en parentesis y el format buscara las llaves y las
sustituira por el valor q le he dado entre parentesis'''

' el texto que esta dentro del print tambien es un objeto\nde python y tiene metodos, como el format. El format\npuedo pasarle parlabras com parametros, solo debo ponelas\nen parentesis y el format buscara las llaves y las\nsustituira por el valor q le he dado entre parentesis'

In [ ]:
print('Hola, {}'.format('Andrea'))

Hola, Andrea


In [ ]:
print('Hola, {}! Esta es su visita número {}'.format('Andrea', 32))

Hola, Andrea! Esta es su visita número 32


In [ ]:
print('Hola, {nombre}! Esta es su visita número {visita}'.format(visita=32, nombre='Andrea'))

Hola, Andrea! Esta es su visita número 32


In [ ]:
'''como vemos dentro del format incluso puedo
asignar variables'''


'como vemos dentro del format incluso puedo\nasignar variables'

## *f-Strings*

https://docs.python.org/3.6/reference/lexical_analysis.html#f-strings

In [ ]:
'''este es un metodo reciente. como vemos en el siguiente
ejemplo la f al inicio sustituira el texto con los
 valores del las variables, la f buscará las variables para
 hacer la sustitución
 si no ponemos la f no susutituira los valores'''

'este es un metodo reciente. como vemos en el siguiente\nejemplo la f al inicio sustituira el texto con los\n valores del las variables, la f buscará las variables para\n hacer la sustitución\n si no ponemos la f no susutituira los valores'

In [ ]:
nombre = 'Andrea'
visita = 32

In [ ]:
print('Hola, {nombre}! Esta es su visita número {visita}')

Hola, {nombre}! Esta es su visita número {visita}


In [ ]:
print(f'Hola, {nombre}! Esta es su visita número {visita}')

Hola, Andrea! Esta es su visita número 32


# <font color=green> 3. TRABAJANDO CON LISTAS
---

# 3.1 Creando listas

Listas son secuencias **mutables** que son utilizadas para guardar
colecciones de objetos, generalmente homogéneos.
Pueden ser construídas de varias formas:
```
- Utilizando un par de corchetes: [ ], [ 1 ]
- Utilizando un par de corchetes con objetos separados por comas: [ 1, 2, 3 ]
```

In [ ]:
Accesorios = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

### Lista con tipos de datos variados

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Cerraduras eléctricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimedia', 'Frenos ABS'], 106161.94]

In [ ]:
Carro_1

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Cerraduras eléctricas', 'Piloto automático'],
 88078.64]

In [ ]:
Carro_2

['Passat',
 'Motor Diesel',
 1991,
 5712.0,
 False,
 ['Central multimedia', 'Frenos ABS'],
 106161.94]

In [ ]:
#crearemos una lista con las listas q tenemos

Carros = [Carro_1, Carro_2]

In [ ]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Cerraduras eléctricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimedia', 'Frenos ABS'],
  106161.94]]

# 3.2 Operaciones con listas

https://docs.python.org/3.6/library/stdtypes.html#common-sequence-operations

In [ ]:
"""
en el link se muestra un catálogo completo de tipos de
operaciones q se pueden realizar con listas

veremos X in A
este busca si el elemento X esta en la lista A
esto sirve para identificar una caracteristica especifica en
nuestra lista y si esta trabajar con ella
"""

'\nen el link se muestra un catálogo completo de tipos de\noperaciones q se pueden realizar con listas\n\nveremos X in A\neste busca si el elemento X esta en la lista A\nesto sirve para identificar una caracteristica especifica en\nnuestra lista y si esta trabajar con ella\n'

## *x in A*

Devuelve **True** si un elemento de la lista *A es igual a x*.

In [ ]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
"""
nuestro elemento x sera cerraduras electricas, busquemos
"""

'Cerraduras eléctricas' in Accesorios

True

In [ ]:
# y si no existe? sera False

'4 x 4' in Accesorios

False

In [ ]:
# podemos preguntarle si  X no esta en A

'Cerraduras eléctricas' not in Accesorios

False

In [ ]:
'4 x 4' not in Accesorios

True

## *A + B*

Concatena las listas *A y B*.

In [ ]:
"""
otro operador el A + B
este operador no solo suma sino que concatena las listas

en el siguiente ejemplo tenemos la lista de accesorios
dividad en dos asi q vamos a juntas ambas listas en
una sola
"""

'\notro operador el A + B\neste operador no solo suma sino que concatena las listas\n\nen el siguiente ejemplo tenemos la lista de accesorios\ndividad en dos asi q vamos a juntas ambas listas en\nuna sola\n'

In [ ]:
A = ['Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero']
B = ['Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de lluvia']

In [ ]:
A + B

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *len(A)*

Tamaño de la lista A.

In [ ]:
"""
este operados nos permite saber el tamaaño
o sea cuántos elementos tiene mi lista
"""

'\neste operados nos permite saber el tamaaño\no sea cuántos elementos tiene mi lista\n'

In [ ]:
len(Accesorios)

6

# 3.3 Selecciones en listas

## *A[ n ]*

Devuelve el n-ésimo objeto de la lista *A*.

<font color=red>**Observación:**</font> Listas tienen indexación con inicio en cero.

In [ ]:
"""
veremos formas de hacer selecciones en las listas
o sea a extraer los elementos

cada elemento tiene un orden un indice, para extraer el
elemento necesitamos saber qué posición tiene,
recordemos que el primer indice es 0
 el método A[n]
 lista[índice]
"""

'\nveremos formas de hacer selecciones en las listas\no sea a extraer los elementos\n\ncada elemento tiene un orden un indice, para extraer el\nelemento necesitamos saber qué posición tiene,\nrecordemos que el primer indice es 0\n el método A[n]\n lista[índice]\n'

In [ ]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
Accesorios[0]

'Cerraduras eléctricas'

In [ ]:
Accesorios[1]

'Piloto automático'

In [ ]:
# si yo quiero extraer el último elemento
Accesorios[5]

'Sensor de lluvia'

In [ ]:
#si no sé qué # de indice tiene...

Accesorios[-1]

'Sensor de lluvia'

In [ ]:
# tengo una lista donde sus elementos son listas
# cómo extraigo ?

Carros



[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Cerraduras eléctricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimedia', 'Frenos ABS'],
  106161.94]]

In [ ]:
#quiero el primer elemento

Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Cerraduras eléctricas', 'Piloto automático'],
 88078.64]

In [ ]:
# y ahora quiero el primer elemento, asi acceso al
#priemer elemento y dentro de este al primer
#elemento de nuevo

Carros[0][0]

'Jetta Variant'

In [ ]:
#quiero el penultimo elemento q es otra lista

Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Cerraduras eléctricas', 'Piloto automático'],
 88078.64]

In [ ]:
#el ultimo elemento es -1 pero yo quiero
#el penultimo es -2
Carros[0][-2]

['Cerraduras eléctricas', 'Piloto automático']

In [ ]:
'''ahora quieroel segundo elemento, del penultimo
elemento del primer elemento.
osea necesito acceder a la primer lista,
luego al penultimo elemento de esa lista
y luego al segundo elemento de esta.'''

Carros[0][-2][1]

'Piloto automático'

## *A[ i : j ]*

Recorta la lista A desde el índice i hasta j. En este recorte el elemento con índice i **es incluído** y el elemento con índice j **no es incluído** en el resultado.

In [ ]:
"""
quiero accesar no solo a un elemento sino a varios
a esto se le llama recortas listas
para esto usaremos
A[i:j]

A sera la lista
i sera el primer elemento desde donde queremos cortar
j sera el ultimo elemento hasta donde queremos cortar

tengamos en cuenta q en el corte el i sera incluido
pero el indice j no sera tomado en cuenta en el
resultado final

veamos
"""

'\nquiero accesar no solo a un elemento sino a varios\na esto se le llama recortas listas\npara esto usaremos\nA[i:j]\n\nA sera la lista\ni sera el primer elemento desde donde queremos cortar\nj sera el ultimo elemento hasta donde queremos cortar\n\ntengamos en cuenta q en el corte el i sera incluido\npero el indice j no sera tomado en cuenta en el\nresultado final\n\nveamos\n'

In [ ]:
Accesorios

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
"""quiero desde asientos de cuero hasta sensor de
estacionamiento"""

'quiero desde asientos de cuero hasta sensor de\nestacionamiento'

In [ ]:
Accesorios[2:5]

['Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento']

In [ ]:
#aqui es cuando no sé qué indice tienen los últimos
#elementos
Accesorios[2:-1]

['Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento']

In [ ]:
"""y si quiero incluir hasta el último elemento
pongo el # del indice que deberia segur
en mi lista si tengo 6 elementos, 5 indices el último
indice q hay es 5 asi que debo poner el 6
para q aparezca el último elemento
"""

Accesorios[2:6]

['Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# y si no sé el último indice ?...

Accesorios[2:]

['Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# y si quiero emepezar el corte desde el primer elemento
#puedo obviar ese primer elemento

Accesorios[:5]

['Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento']

# 3.4 Métodos en listas

https://docs.python.org/3.6/library/stdtypes.html#mutable-sequence-types

## *A.sort()*

Ordena la lista *A*.

In [ ]:
"""
recordemos q las listas son un objeto y estos tienen
metodos funciones etc

veremos los metodos

sort()

este metodo ordena los elementos alfabeticamente

A.sort()
listas.sort()
"""

'\nrecordemos q las listas son un objeto y estos tienen\nmetodos funciones etc\n\nveremos los metodos\n\nsort()\n\neste metodo ordena los elementos alfabeticamente\n\nA.sort()\nlistas.sort()\n'

In [ ]:
Accesorios.sort()
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *A.append(x)*

Añade el elemento *x al final de la lista A*

In [ ]:
"""
este metodo inserta un nuevo elemto
al final de nuestra lista
"""

Accesorios.append('4 x 4')
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 '4 x 4']

## *A.pop(i)*

Elimina y devuelve el elemento de índice i de la lista *A*.

<font color=red>**Observación:**</font> Por *defecto* el método *pop()* elimina y devuelve el último elemento de una lista.

In [ ]:
"""
este metodo elimina elementos de nuestra lista
"""

#Accesorios.pop() si yo no pongo un elemento
#aqui entre parentesis eliminara el último
#elemento de nuestra lista

#si quiero eleiminar uno en concreto
# pongo el indice de ese elemento

'\neste metodo elimina elementos de nuestra lista\n'

In [ ]:
Accesorios.pop()
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
# quiero eliminar un elemento en concreto

Accesorios.pop(3)

'Piloto automático'

In [ ]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

## *A.copy()*

Crea una copia de la lista *A*.

<font color=red>**Observación:**</font> El mismo resultado puede ser obtenido con el seguinte código:
```
A[:]
```

In [ ]:
# este metodo copiara la lista

""" en programación una manera de copias es la siguiente
pero qué pasa si con figuramos ó cambiamos
la lista 2 q sera la copia, veamos
"""

Accesorios_2 = Accesorios
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
Accesorios_2.append('4 x 4')
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 '4 x 4']

In [ ]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 '4 x 4']

In [ ]:
"""
como vemos al hacer la copia de esta manera si
modificamos una lista, ambas estaran modificadas
aqui en python solo le creamos un nuevo nombre
asi que la puedo llamar de con cualquiera de los
2, pero es la misma lista. no es una copia de esta

la forma correcta es con el metodo copy()

veamos
"""

'\ncomo vemos al hacer la copia de esta manera si\nmodificamos una lista, ambas estaran modificadas\naqui en python solo le creamos un nuevo nombre\nasi que la puedo llamar de con cualquiera de los\n2, pero es la misma lista. no es una copia de esta\n\nla forma correcta es con el metodo copy()\n\nveamos\n'

In [ ]:
#eliminemos el elemento q no necesitamos

Accesorios.pop()
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
Accesorios_2

#como vemos es la misma lista y se han modificado


['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
#hagamos la copia

Accesorios_2 =Accesorios.copy()
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
Accesorios_2.append('4 x 4')
Accesorios_2

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 '4 x 4']

In [ ]:
#verifiquemos q nuestra primer lista no se modifico
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
"""
hay otra forma de copiar una lista
"""

Accesorios_3 = Accesorios[:]
Accesorios_3

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

# <font color=green> 4. ESTRUCTURAS DE REPETICIÓN Y CONDICIONALES
---

# 4.1 Instrucción *for*

#### Formato estándar

```
for <variable> in <coleccion>:
    <instrucciones>
```

### Loops con listas

In [ ]:
Accesorios = ['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

Accesorios

['Aire acondicionado',
 'Asientos de cuero',
 'Cerraduras eléctricas',
 'Sensor de estacionamiento',
 'Sensor de lluvia']

In [ ]:
"""ahora recorreremos cada uno de los elementos con for
for
i sera la variable q representa cada elemento
Accesorios sera la coleccionq  queremos iterar esta vez
"""

for i in Accesorios:
  print(i)


#aqui ya no esta en lista ya no hay corchetes, solo
#hay un print

Aire acondicionado
Asientos de cuero
Cerraduras eléctricas
Sensor de estacionamiento
Sensor de lluvia


###  List comprehensions

https://docs.python.org/3.6/tutorial/datastructures.html#list-comprehensions

*range()* -> https://docs.python.org/3.6/library/functions.html#func-range

In [ ]:
"""
esta es una forma mas resumida de crear una lista
par ello usaremos una función q se llama range
esta nos ayuda a crear valores secuenciales d forma
ordenada, veamos
"""

'\nesta es una forma mas resumida de crear una lista\npar ello usaremos una función q se llama range\nesta nos ayuda a crear valores secuenciales d forma\nordenada, veamos\n'

In [ ]:
#quiero una lista de 10 elementos

range(10)

range(0, 10)

In [ ]:
#ahora quiero una lista con un rango de valores ordenados
# de 0 a 10
# recordemos q para crear la lista uso list
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
#recorreremos cada elemento

for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# ahora quiero printar el valor al cuadrado de cada
#elemento
#recordemos  que ** es elevación en python

for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
#ahora quiero guardarlos en una lista
# creare una lista vacia

cuadrado=[]

In [ ]:
#ahora almacenare cada elemento en la lista

for i in range(10):
  cuadrado.append(i ** 2)

cuadrado

#aqui para llamar a la lista me salgo de la identación
#por q si lo hago dentro el resultado sera diferente
#y  ya no quiero hacer nada dentro del for

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
#cómo hacer lo anterioro en un sola linea de código

#qué es lo realmente importante en el código anterior
#usemos la list comprenhension

#qué operación estoy realizando con cada elemento?
# qué es lo importante del código anterior?
#tengo la lista, el for, la operacion del for
# q es la elevación al cuadrado. entonces
#veamos cómo podemos mantener esto de una forma más
#simplificada

#primero la operación, en este caso la elvación al cuadrado
#despues el for
# y luego la lista de los elementos

cuadrado = [i**2 for i in range(10)]

In [ ]:
cuadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
#muy bien tenemos el mismo resultado,
"""
primero la operacion dentro del corchete
y luego el for q itera

"""

'\nprimero la operacion dentro del corchete\ny luego el for q itera\n\n'

# 4.2 Loops anidados

In [ ]:
"""
bien, ya sabemos q para iterar necesitamos u loop o
for pero y si tenemos una lista de listas, cómo
puedo recorrerlas?
con un solo loop no se puede se necesitan varios loops
aprendamos de los loops anidados

extraigamos los elementos de las siguientes sub listas
"""

'\nbien, ya sabemos q para iterar necesitamos u loop o\nfor pero y si tenemos una lista de listas, cómo\npuedo recorrerlas?\ncon un solo loop no se puede se necesitan varios loops\naprendamos de los loops anidados\n\nextraigamos los elementos de las siguientes sub listas\n'

In [ ]:
datos = [
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [ ]:
# con el primer loop llegaremmos a las sublistas
for i in datos:
  print(i)

['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia']
['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento']
['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']


In [ ]:
# ahora, cómo llego a los elementos de cada sublista
#cada elemento de mis lista datos es una lista, osea
#que aqui en el for esta representado por i, por tanto
#i representa 3 elementos de mi lista y cada elemento es
# una sublista tambien definidos como
#una coleccion de datos y por esto tambien se le puede
#aplicar un for a este elemento i.

#veamos

for i in datos:
 for item in i:
  print(item)

Llantas de aleación
Cerraduras eléctricas
Piloto automático
Asientos de cuero
Aire acondicionado
Sensor de estacionamiento
Sensor de crepúsculo
Sensor de lluvia
Central multimedia
Techo panorámico
Frenos ABS
4 X 4
Panel digital
Piloto automático
Asientos de cuero
Cámara de estacionamiento
Piloto automático
Control de estabilidad
Sensor crepuscular
Frenos ABS
Transmisión automática
Asientos de cuero
Central multimedia
Ventanas eléctricas


In [ ]:
"""
bien en la celda anterior logramos llegar a cada
elemento de las sublistas

tenemos 2 for, con el primero llegamos a las
sublistas

for i in datos

aqui datos es la lista completa, e i representa cada
elemento o sea cada sublista.

con el segundo for

for item in i

item es cada elemento de las sublistas q en este caso
a las sublistas les hemos dado el nombre ó las hemos
respresentado con i, asi que
este for recorrera cada item de i osea
cada elemento de las sublistas.

"""


'\nbien en la celda anterior logramos llegar a cada\nelemento de las sublistas\n\ntenemos 2 for, con el primero llegamos a las\nsublistas\n\nfor i in datos\n\naqui datos es la lista completa, e i representa cada\nelemento o sea cada sublista.\n\ncon el segundo for\n\nfor item in i\n\nitem es cada elemento de las sublistas q en este caso\na las sublistas les hemos dado el nombre ó las hemos\nrespresentado con i, asi que\neste for recorrera cada item de i osea\ncada elemento de las sublistas.\n\n'

In [ ]:
#ahora los elementos ya estan sueltos, quiero
#guardarlos en una variable

Accesorios = []

for i in datos:
 for item in i:
  Accesorios.append(item)

Accesorios



['Llantas de aleación',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de crepúsculo',
 'Sensor de lluvia',
 'Central multimedia',
 'Techo panorámico',
 'Frenos ABS',
 '4 X 4',
 'Panel digital',
 'Piloto automático',
 'Asientos de cuero',
 'Cámara de estacionamiento',
 'Piloto automático',
 'Control de estabilidad',
 'Sensor crepuscular',
 'Frenos ABS',
 'Transmisión automática',
 'Asientos de cuero',
 'Central multimedia',
 'Ventanas eléctricas']

In [ ]:
"""
bien, aqui creamos la variable o la lista
Accesorios y con el metodo append le
añadimos los elementos de cada sublista
q recorrimos q en este caso los representamos
com item.

Ahora tengo una lista q ya tiene elementos
individulaes  y asi ya puedo usarlos. pero
aun tenemos elementos repetidos

"""

'\nbien, aqui creamos la variable o la lista\nAccesorios y con el metodo append le\nañadimos los elementos de cada sublista\nq recorrimos q en este caso los representamos\ncom item.\n\nAhora tengo una lista q ya tiene elementos\nindividulaes  y asi ya puedo usarlos. pero\naun tenemos elementos repetidos\n\n'

## *set()*

https://docs.python.org/3.6/library/stdtypes.html#types-set

https://docs.python.org/3.6/library/functions.html#func-set

In [ ]:
"""
los links muestran en qué momentos se usa el método
set, uno de estos momentos en los q se usa es para
remover duplicidad de alguna colección

"""

set(Accesorios)




{'4 X 4',
 'Aire acondicionado',
 'Asientos de cuero',
 'Central multimedia',
 'Cerraduras eléctricas',
 'Control de estabilidad',
 'Cámara de estacionamiento',
 'Frenos ABS',
 'Llantas de aleación',
 'Panel digital',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de crepúsculo',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 'Techo panorámico',
 'Transmisión automática',
 'Ventanas eléctricas'}

In [ ]:
"""
bien aqui se elimino la duplicidad, incluso
organizo en orden alfabetico
pero ya no es unalista
ahora es un diccionario que tiene llaves
cómo convertir esto a lista?

veamos

"""

list(set(Accesorios))

['Sensor de estacionamiento',
 'Panel digital',
 'Aire acondicionado',
 'Sensor de crepúsculo',
 'Cámara de estacionamiento',
 'Sensor de lluvia',
 'Central multimedia',
 'Asientos de cuero',
 'Frenos ABS',
 'Cerraduras eléctricas',
 '4 X 4',
 'Sensor crepuscular',
 'Ventanas eléctricas',
 'Piloto automático',
 'Techo panorámico',
 'Control de estabilidad',
 'Llantas de aleación',
 'Transmisión automática']

### List comprehensions

In [ ]:
"""cómo realizar lo anterior con list comprenhension?
Accesorios = []

for i in datos:
 for item in i:
  Accesorios.append(item)

Accesorios

la operacion es agregar los items a la lista accesorios
y luego ponemos los for
"""
#lista= operacion, for( los for van en orden)
Accesorios = [item for i in datos for item in i]
Accesorios



['Llantas de aleación',
 'Cerraduras eléctricas',
 'Piloto automático',
 'Asientos de cuero',
 'Aire acondicionado',
 'Sensor de estacionamiento',
 'Sensor de crepúsculo',
 'Sensor de lluvia',
 'Central multimedia',
 'Techo panorámico',
 'Frenos ABS',
 '4 X 4',
 'Panel digital',
 'Piloto automático',
 'Asientos de cuero',
 'Cámara de estacionamiento',
 'Piloto automático',
 'Control de estabilidad',
 'Sensor crepuscular',
 'Frenos ABS',
 'Transmisión automática',
 'Asientos de cuero',
 'Central multimedia',
 'Ventanas eléctricas']

In [ ]:
#Ahora en el anterior linea de código no eliminamos
#los duplicados, hagamoslo

Accesorios = set([item for i in datos for item in i])
Accesorios

{'4 X 4',
 'Aire acondicionado',
 'Asientos de cuero',
 'Central multimedia',
 'Cerraduras eléctricas',
 'Control de estabilidad',
 'Cámara de estacionamiento',
 'Frenos ABS',
 'Llantas de aleación',
 'Panel digital',
 'Piloto automático',
 'Sensor crepuscular',
 'Sensor de crepúsculo',
 'Sensor de estacionamiento',
 'Sensor de lluvia',
 'Techo panorámico',
 'Transmisión automática',
 'Ventanas eléctricas'}

In [ ]:
#como vemos ya no es una lista, recordemos q set no
#devuelve lista asi q tenemos q convertirlo a lista

Accesorios = list(set([item for i in datos for item in i]))
Accesorios

['Sensor de estacionamiento',
 'Panel digital',
 'Aire acondicionado',
 'Sensor de crepúsculo',
 'Cámara de estacionamiento',
 'Sensor de lluvia',
 'Central multimedia',
 'Asientos de cuero',
 'Frenos ABS',
 'Cerraduras eléctricas',
 '4 X 4',
 'Sensor crepuscular',
 'Ventanas eléctricas',
 'Piloto automático',
 'Techo panorámico',
 'Control de estabilidad',
 'Llantas de aleación',
 'Transmisión automática']

In [ ]:
#ahora sí accesorios es una lista, con elementos únicos

# 4.3 Instrucción *if*

#### Formato estándar

```
if <condicion>:
     <instrucciones en caso la condición sea verdadera>
```

In [ ]:
"""
esta la usamos cuando queremos hacer tests
ó cuando queremos comparar valores

tenemos los operadores de comparación
== igual
!= diferente
> mayor
< menor
>= mayor iguial
<= menor igual


y operadores lógicos q nos ayudaran a probar
nuestra condicion dentro de la instrucción

and - y
or - ó
not - no
"""

'\nesta la usamos cuando queremos hacer tests\nó cuando queremos comparar valores\n\ntenemos los operadores de comparación\n== igual\n!= diferente\n> mayor\n< menor\n>= mayor iguial\n<= menor igual\n\n\ny operadores lógicos q nos ayudaran a probar\nnuestra condicion dentro de la instrucción\n\nand - y\nor - ó\nnot - no\n'

### Operadores de comparación: $==$, $!=$, $>$, $<$, $>=$, $<=$
### y
### Operadores lógicos: $and$, $or$, $not$

In [ ]:
# 1º objeto de la lista - Nombre del vehículo
# 2º objeto de la lista - Año de fabricación
# 3º objeto de la lista - Vehículo es cero km?

datos = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
datos

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
#queremos extraer los elementos de vehiculos 0 km
# primero identificar q sea 0 km
#debemos verificar si el 3 elemento de cada sublista es true,
#para ello usamos if

#primero un for para recorrer
"""
i seran la representacion de cada sublista
en la condicion voy a la sublista con
i y lo q quiero comparar es la ultima pocision
de cada sublista, la última pocision en este caso
tiene es el indice 2 asi q dire i[2]
operador comparativo de igualdad ==
contra el True y ahora pido que me imprima
solo los que cumplen con la condición , osea q
me imprima las sublistas donde su
ultima pocision es True
"""

for i in datos:
  if (i [2] == True):
   print(i)

['DS5', 2019, True]
['A5', 2019, True]


In [ ]:
#ahora guardare esos resultados en una lista

cero_km_T = []

for i in datos:
  if (i [2] == True):
   cero_km_T.append(i)

cero_km_T



[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
#ahora quiero guardar los vehiculos q no son 0km


cero_km_F = []

for i in datos:
  if (i [2] == False):
   cero_km_F.append(i)

cero_km_F

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

### List comprehensions

In [ ]:
#hagamos los anterior con list comprenhension


cero_km_T = [i for i in datos if (i [2] == True)]
cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
cero_km_F = [i for i in datos if (i [2] == False)]
cero_km_F

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 4.4 Instrucciones *if-else* y *if-elif-else*

#### Formato estándar

```
if <condicion>:
    <instrucciones en caso la condición sea verdadera>
else:
    <instrucciones en caso la condición no sea verdadera>
```

In [ ]:
"""
if-else
esta nos indica q cuando una condicion  se cumple
ponemos las instrucciones en la siguiente linea
si no se cumple ponemos else y luego las
instrucciones necesarias
"""

'\nif-else\nesta nos indica q cuando una condicion  se cumple\nponemos las instrucciones en la siguiente linea\nsi no se cumple ponemos else y luego las\ninstrucciones necesarias\n'

In [ ]:
datos

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
"""
tenemos q crear dos listas vacias
en una sola linea
"""

cero_km_F, cero_km_T = [], []

"""
añadimos el else luego de la instruccion del if
y le ponemos su propia instrucción
"""

for i in datos:
  if (i [2] == False):
   cero_km_F.append(i)
  else:
    cero_km_T.append(i)



In [ ]:
cero_km_F


[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
cero_km_T

[['DS5', 2019, True], ['A5', 2019, True]]

#### Formato estándar

```
if <condicion 1>:
    <instrucciones en caso la condición 1 sea verdadera>
elif <condicion 2>:
    <instrucciones en caso la condición 2 sea verdadera>
elif <condicion 3>:
    <instrucciones en caso la condición 3 sea verdadera>
                        .
                        .
                        .
else:
    <instrucciones en caso las condiciones anteriores no sean verdaderas>
```

In [ ]:
datos

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
"""
bien aqui usaremos el año de fabricacion para el ejemplo
y usar el if elif y else para categorizarlos
"""

'\nbien aqui usaremos el año de fabricacion para el ejemplo\ny usar el if elif y else para categorizarlos\n'

In [ ]:
print('AND')
print(f'(True and True) el resultado es: {True and True}')
print(f'(True and False) el resultado es: {True and False}')
print(f'(False and True) el resultado es: {False and True}')
print(f'(False and False) el resultado es: {False and False}')

AND
(True and True) el resultado es: True
(True and False) el resultado es: False
(False and True) el resultado es: False
(False and False) el resultado es: False


In [ ]:
print('OR')
print(f'(True or True) el resultado es: {True or True}')
print(f'(True or False) el resultado es: {True or False}')
print(f'(False or True) el resultado es: {False or True}')
print(f'(False or False) el resultado es: {False or False}')

OR
(True or True) el resultado es: True
(True or False) el resultado es: True
(False or True) el resultado es: True
(False or False) el resultado es: False


In [ ]:
# voy a crear 3 listas para guardar alli los datos, voy a
#separar y categorizar por año en cada lista
A,B,C = [], [],[]

In [ ]:
#recorro la lista datos

for i in datos:
  if (i[1] <= 2000):
    A.append(i)
    # bien aqui uso i para representar las sublistas
    #[1 ] pocision del año de fabricacion que es lo
    #que quiero comparar
    #<= 2000 operador de comparacion y comparación
    #y si es cierto guardo en lista A
    '''  elif(i[1]>2000 i[1<=2010])  aqui deberia de
    hacer dos condiciones pero para ello usare
    and porq necesito q ambas sean verdaderas'''
  elif(i[1]>2000 and i[1]<=2010):
    B.append(i)
  else:
    C.append(i)    #el eslse guardara todo el restante q no cumple las
                   #condiciones anteriores

In [ ]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [ ]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [ ]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
"""
cuando usamos and esto solo se cumplira cuando
ambas condiciones sean verdaderas, si una de las dos
es falsa la condicion no se cumple y por tanto
no se ejecuta

cómo saber qué combinacion podemos usar. arriba
vemos anotaciones de usar or y and
"""

'\ncuando usamos and esto solo se cumplira cuando\nambas condiciones sean verdaderas, si una de las dos\nes falsa la condicion no se cumple y por tanto\nno se ejecuta\n\ncómo saber qué combinacion podemos usar. arriba\nvemos anotaciones de usar or y and\n'

In [ ]:
A,B,C = [],[],[]

for i in datos:
  if (i[1] <= 2000):
    A.append(i)
  elif(2000 < i[1]<=2010): #forma simplicada
    B.append(i)
  else:
    C.append(i)

In [ ]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [ ]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [ ]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# <font color=green> 5. NUMPY BÁSICO
---

Numpy es la abreviación de Numerical Python y es uno de los paquetes más importantes para procesamiento numérico en Python. Numpy ofrece la base para la mayoría de los paquetes de aplicaciones científicas que usen datos numéricos en Python (estructuras de datos y algoritmos). Pueden destacarse los siguientes recursos que el paquete Numpy contiene:

- Un poderoso objeto array multidimensional;
- Funciones matemáticas sofisticadas para operaciones con arrays sin la necesidad de utilización de bucles *for*;
- Recursos de algebra linear y generación de números aleatórios

Además de sus obvios usos científicos, el paquete NumPy también es muy utilizado en análisis de datos como un eficiente contenedor multidimensional de datos genéricos para transporte entre diversos algoritmos y bibliotecas en Python.

**Versión:** 1.18.4

**Instalación:** https://scipy.org/install.html

**Documentación:** https://numpy.org/doc/1.18/

### Paquetes

Existen diversos paquetes Python disponibles para download en internet. Cada paquete tiene como objetivo la solución de determinado tipo de problema y para esto son desarrollados nuevos tipos, funciones y métodos.

Algunos paquetes son bastante utilizados en un contexto de ciencia de datos, como por ejemplo:

- Numpy
- Pandas
- Scikit-learn
- Matplotlib

Algunos paquetes no son distribuidos en la instalación estándar de Python. En este caso debemos instalar los paquetes que necesitamos en nuestro sistema para poder utilizar sus funcionalidades.

### Importando todo el paquete

In [ ]:
import numpy

https://numpy.org/doc/1.16/reference/generated/numpy.arange.html

In [ ]:
'''
usaremos el metdo arange, este metodo genera
una lista con valores secuenciales de cierto
tamaño, este metodo esta dentro de numpy'''

numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando todo el paquete y asignándole un nuevo nombre

In [ ]:
import numpy as np

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Importando parte del paquete

In [ ]:
''' cuando importamos un paquete este importa
todos los metodos q ocupan toda nuestra memoria
asi q podemos importar solo el metodo q usaremos
'''
from numpy import arange

In [ ]:
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5.1 Creando arrays Numpy

In [ ]:
import numpy as np

### A partir de listas

https://numpy.org/doc/1.16/user/basics.creation.html

In [ ]:
km = np.array([1000, 2300, 4987, 1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)
#aqui vemos qué tipo de dato es km
# es un array

numpy.ndarray

https://numpy.org/doc/1.16/user/basics.types.html

In [ ]:
#aqui ya sabems q km es numpy y podemos usar en el
#los metodos de numpy, como el dtype
#que me dice qué tipo de datos tiene km
km.dtype


dtype('int64')

### A partir de datos externos

https://numpy.org/doc/1.16/reference/generated/numpy.loadtxt.html

In [ ]:
#generaremos un array a partir de datos externos,
#en este caso un archivo de texto, este es un archivo
#unidimensional porq no tiene columnas y filas
#pero con numpy podemos generar varias dimensiones

In [ ]:
#fname es nombre del archivo
km = np.loadtxt(fname= 'carros-km.txt', dtype = int)

In [ ]:
km

array([ 44410,   5712,  37123,      0,  25757,  10728,      0,  77599,
        99197,  37978,  12859,   8052,  89773,      0,  41457, 115607,
        46449,      0,  37086,  15173, 101193,      0,  98079, 102959,
            0,      0,   5795,      0,  58848,  94381,  30163,  53332,
        17720,  33808,  90684,  43975,      0,      0,   5526,      0,
        93415,  40762,      0,  86302,      0,   9755,  69945,   2395,
            0,  80349,  85554,  50496,  67716,  93947,  35345,  81007,
       119513,      0,      0,      0,      0,      0, 118895,  48509,
       100912,  95649,      0,  90495,      0,  29132,  23802,  84992,
        54395,  26731,  44329, 118236, 113808,    610,      0,      0,
        12887,  79607,  90924,  42733,      0,      0, 117714, 113885,
            0,  30511,  74867, 119760,   8356,  64247,  88661,   4539,
       110116,  33215,  92001,      0,  81708,  70641,      0,  91277,
        26544,  52596,  47503,  89056,  28834, 110564,  56638,  17357,
      

### Arrays con dos dimensiones

In [ ]:
datos = [
    ['Llantas de aleación', 'Cerraduras eléctricas', 'Piloto automático', 'Asientos de cuero', 'Aire acondicionado', 'Sensor de estacionamiento', 'Sensor de crepúsculo', 'Sensor de lluvia'],
    ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4', 'Panel digital', 'Piloto automático', 'Asientos de cuero', 'Cámara de estacionamiento'],
    ['Piloto automático', 'Control de estabilidad', 'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática', 'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']
]
datos

[['Llantas de aleación',
  'Cerraduras eléctricas',
  'Piloto automático',
  'Asientos de cuero',
  'Aire acondicionado',
  'Sensor de estacionamiento',
  'Sensor de crepúsculo',
  'Sensor de lluvia'],
 ['Central multimedia',
  'Techo panorámico',
  'Frenos ABS',
  '4 X 4',
  'Panel digital',
  'Piloto automático',
  'Asientos de cuero',
  'Cámara de estacionamiento'],
 ['Piloto automático',
  'Control de estabilidad',
  'Sensor crepuscular',
  'Frenos ABS',
  'Transmisión automática',
  'Asientos de cuero',
  'Central multimedia',
  'Ventanas eléctricas']]

In [ ]:
#generaremos un array np en base a la lista de datos que tenemos

Accesorios = np.array(datos)

In [ ]:
Accesorios

array([['Llantas de aleación', 'Cerraduras eléctricas',
        'Piloto automático', 'Asientos de cuero', 'Aire acondicionado',
        'Sensor de estacionamiento', 'Sensor de crepúsculo',
        'Sensor de lluvia'],
       ['Central multimedia', 'Techo panorámico', 'Frenos ABS', '4 X 4',
        'Panel digital', 'Piloto automático', 'Asientos de cuero',
        'Cámara de estacionamiento'],
       ['Piloto automático', 'Control de estabilidad',
        'Sensor crepuscular', 'Frenos ABS', 'Transmisión automática',
        'Asientos de cuero', 'Central multimedia', 'Ventanas eléctricas']],
      dtype='<U25')

In [ ]:
#este array q generamos tiene varias listas q tiene
#varias dimensiones

km.shape

#este metodo muestra en este caso
#como tiene una sola dimension, tiene
#una sola fila asi q muestra
#en este caso 258 elementos

(258,)

In [ ]:
Accesorios.shape

#este tiene varias dimensiones asi que muestra
#(numero de filas, numero de columnas)

(3, 8)

### Comparando desempeño con listas

In [ ]:
#array numpy

np_array= np.arange(1000000)

In [ ]:
#lista de python

py_list = list(range(1000000))

In [ ]:
#bien tenemos ambas listas, de los mismos elementos
#cuál demorara menos en ser recorrida
#%time captara el tiempo q demorara el loop
# q crearemos, este loop recorrera 100 veces
# y cada vez q recorra los elementos lo multiplicara por 2
# y hara esto 100 veces
#aqui el _ pide q se guarde el último calculo hecho ó
#tambien aqui sustituye la variable X pero como no
#se esta usando la variable x en ningun momento
#solo se ignora y para esto se usa el _

%time  for _ in range(100): np_array *= 2

CPU times: user 95.5 ms, sys: 0 ns, total: 95.5 ms
Wall time: 117 ms


In [ ]:
#aqui uso la x, recorremos la lista y cada
#elemento se multiplica por 2, la x representa
#los elementos y esto se repetira 100veces


%time  for _ in range(100): py_list = [x*2 for x in py_list]


CPU times: user 10.4 s, sys: 2.63 s, total: 13 s
Wall time: 13.7 s


In [ ]:
# como vemos la lista de python tardo casi 16.3 segundos pero
# en numpy se tardo solo 86.4 milisegundos por esto
#para grandes cantidades de datos numpy es mas optimo

# 5.2 Operaciones aritméticas con arrays Numpy

### Operaciones entre arrays y constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
años = [2003, 1991, 1990, 2019, 2006]

In [ ]:
"""
quiero calcular la edad de cada vehiculo
q seria con el año actual - el año de fabricacion
"""
# calculemos:

#  edad = 2020 - años

#ups aqui tenemso un error, no podemos hacer una
#operacion entre str(años) e int(2020). Por eso en listas
# no es recomendable para operaciones sino mas bien
# numpy arrays

'\nquiero calcular la edad de cada vehiculo\nq seria con el año actual - el año de fabricacion\n'

In [ ]:
#haremos excta,ente la misma operacion
#pero con arrays

km = np.array([44410., 5712., 37123., 0., 25757.])
años = np.array([2003, 1991, 1990, 2019, 2006])

In [ ]:
edad = 2020 - años

In [ ]:
edad

array([17, 29, 30,  1, 14])

In [ ]:
'''
como vemos aqui logramos combinar str e int
'''

'\ncomo vemos aqui logramos combinar str e int\n'

### Operaciones entre arrays

In [ ]:
'''
km promedio de cada vehiculo
necesItamos el km_total del vehiculo / entre
la edad de cada vehiculo q esta en edad
'''

km_media = km /edad

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

In [ ]:
'''
aqui python recogio cada valor q tiene el array km
y lo dividio entre cada valor de edad'''

#verifiquemos haceindolo manualmente
#km / edad
44410. / 17



2612.3529411764707

In [ ]:

'''asi con array numpy no necesitamos
iterar toda la lista sino q él solito hace todo'''

'asi con array numpy no necesitamos\niterar toda la lista sino q él solito hace todo'

### Operaciones con arrays de dos dimensiones

In [ ]:
#creamos un array de dos dimensiones
# km sera la primer dimension
#años sera la otra dimension
datos = np.array([km, años])

In [ ]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
datos.shape

(2, 5)

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
datos[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
#km_media = km / edad (año actual - año fabricacion)
km_media = datos[0] / (2020 - datos[1])

In [ ]:
km_media

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

# 5.3 Selecciones con arrays Numpy

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

![1410-img02.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img02.png)

### Indexación

<font color=red>**Observación:**</font> La indexación tiene inicio en cero.

In [ ]:
#para practicarlo usaremos contador
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#primer elemento
contador[0]

0

In [ ]:
#ultimo elemento
contador[9]

9

In [ ]:
#ultimo
contador[-1]

9

In [ ]:
#datos es bidimensional asi q el primer elemento
#es una lista de elementos
datos[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [ ]:
#para llegar al primer elemento de esa lista entonces
datos[0][0]

44410.0

In [ ]:
#el tercer elemento de mi segunda lista
datos[1][2]

1990.0

## <font color=green>**Consejo:**</font>
### *ndarray[ linea ][ columna ]* o *ndarray[ linea, columna ]*

In [ ]:
#  ⬆ aqui vemos las dos formas de escribirlo

In [ ]:
#podemos poner el nombre del array q en este caso es datos, la linea q es 1 y la columna q es 2
datos[1][2]

1990.0

In [ ]:
#podemos tambien poner el nombre del
#array y con un unico corchete poner
#la pocision de la fila, posicion de columna

datos[1,2]

1990.0

 ### Particiones

La sintaxis para realizar particiones en un array Numpy es $i : j : k$ donde $i$ es el índice inicial, $j$ es el índice final, y $k$ es el indicador de intervalo ($k\neq0$)

<font color=red>**Observación:**</font> En las particiones (*slices*) el objeto con índice i es **incluído** y el objeto con índice j **no es incluído** en el resultado.

![1410-img01.png](https://caelum-online-public.s3.amazonaws.com/1410-pythondatascience/01/1410-img01.png)

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#contador es unidimensional
#contador[i:j:k]
contador[1:4:]

array([1, 2, 3])

In [ ]:
contador[1:8:2]

array([1, 3, 5, 7])

In [ ]:
#aqui dejo los dos indices primeros en blanco
# por tanto ira desde el inicio hasta el final
#quiero pares y el 0 contara como par, hara salto de 2 en 2
contador[::2]

array([0, 2, 4, 6, 8])

In [ ]:
#quiero impares
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
#ARRAY BIDIMENSIONAL
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
#quiero el segundo ytercer vehiculo, 5712 y 37123,
#y quiero sus años correspondientes para ello
#quiero todas las lineas y elijo las columnas

#recordemos el formato
#datos[linea, columna]
datos[::, 1:3:]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [ ]:
#calcular el km promedio de ambos vehículos
#km recorrido / edad del vehiculo (año actual - año fabricacion)

#usaremos el anterior corte como base
#aqui pedire q del corte anterior me traiga solo la primer
#linea q es el km recorrido

#recordemos el formato
#datos[linea, columna][linea ó dimensión a la que quiero aplicarla]
#aqui obtendremos el km recorrido de cada vehículo
datos[::, 1:3:][0]

array([ 5712., 37123.])

In [ ]:
#y la segunda linea sera el año de fabricación
datos[::, 1:3:][1]

array([1991., 1990.])

In [ ]:
#calculamos el km_promedio
#km recorrido / edad del vehiculo (año actual - año fabricacion)
km_promedio = datos[::, 1:3:][0] / (2020 - datos[::, 1:3:][1])
km_promedio

array([ 196.96551724, 1237.43333333])

In [ ]:
#comprobamos haciendo el mismo calculo para todos los vehiculos

datos[0] / (2020 - datos[1])

array([2612.35294118,  196.96551724, 1237.43333333,    0.        ,
       1839.78571429])

### Indexación con array booleano

<font color=red>**Observación:**</font> Selecciona un grupo de líneas y columnas siguiendo las etiquetas o un array booleano.

In [ ]:
#otra forma de hacer cortes con booleanos

contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#aqui quiero seleccionar donde mi contador sea mayor a 5
#como respuesta obtendremos valores booleanos
#

contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
# aqui para seleccionar en vez de [i:j:k] ponemos
# aqui quiero cortar solo los valores
#que sean mayores a 5 osea q cumplan la condicion
#asi q para el corte pondre la codición

contador[contador > 5]

array([6, 7, 8, 9])

In [ ]:
datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
#quiero los vehiculos con año de fabricacion mayor a 2000

datos [1] > 2000

array([ True, False, False,  True,  True])

In [ ]:
#aplicamos la condicion a todo el array datos
#para hacer el corte
#datos[linea, columnas]

datos[::, datos[1]>2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

# 5.4 Atributos y métodos de arrays Numpy

### Atributos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-attributes

In [ ]:
#los metodos y atributos primero veremos
#ATRIBUTOS

datos

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

## *ndarray.shape*

Devuelve una tupla con las dimensiones del array.

In [ ]:
#filas y columnas
datos.shape

(2, 5)

## *ndarray.ndim*

Devuelve el número de dimensiones del array.

In [ ]:
# devolvera el numero de dimensiones este es bidimensional asi q tiee n2
datos.ndim

2

## *ndarray.size*

Devuelve el número de elementos del array.

In [ ]:
#aqui datos tiene 10 elementos entre ambas dimensiones
datos.size

10

## *ndarray.dtype*

Devuelve el tipo de datos de los elementos del array.

In [ ]:
datos.dtype

dtype('float64')

## *ndarray.T*

Devuelve el array transpuesto, es decir, convierte líneas en columnas y viceversa.

In [ ]:
#convierte las columnas a filas y viceversa
datos.T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [ ]:
# hace lo mismo q el T

datos.transpose()

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

### Métodos

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#array-methods

In [ ]:
# Atributos son propiedades o caracteristicas
#de un array y no necesita () al final

 #Metodos son como funciones y las funciones necesitan
 #() porq dentro puede ir un parametro

## *ndarray.tolist()*

Devuelve el array como una lista Python.

In [ ]:
#ya no es un array es una lista
datos.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

## *ndarray.reshape(shape[, order])*

Devuelve un array que contiene los mismos datos con una nueva forma.

In [ ]:
#redimensiona el array de otra forma, los organiza de formaa
#diferente, para ello puedo darle parámetros a tener en cuenta para
#la organización

contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#redimensionare mi array y le dare como páramentro la cantidad
#de columnas y lineas que quiero q tenga
#contador.reshape((linea, columnas))

contador.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:

#yo puedo decrle cómo ordenarse
# si le digo 'C', se ordenara segun el lenguaje C

contador.reshape((5, 2), order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#F es otro lenguaje
contador.reshape((5, 2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
#aqui tenemos dos listas

In [ ]:
km = [44410, 5712, 37123, 0, 25757]
años = [2003, 1991, 1990, 2019, 2006]

In [ ]:
info_carros = km + años
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
#en la celda anterior ya no se entiende bien en qué
#pocision esta qué cosa, esta desordenado, ordenemos con métodos

#convierto la lista a un array, y luego la ordeno
#y le digo cuántas filas y cuántas columnas quiero

np.array(info_carros).reshape((2,5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
#quiero q cada vehiculo osea cada columna, cada
#info de cada carro este en una fila, asi q quiero
# 5 filas 2 columnas
# en cada fila la info de un vehiculo

np.array(info_carros).reshape((5, 2), order = 'F')


array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

## *ndarray.resize(new_shape[, refcheck])*

Cambia la forma y el tamaño del array.

In [ ]:
datos_new = datos.copy()
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
#cabiaremos el tamañao del datos

'''datos_new.resize((3, 5))'''  #ups aqui da error.

#el error noa indica q apesar de haber hecho una copia
 # existe una referencia al original y no podemos modificar,
 #la solucion q se nos plantea es renunciar a la referencia con
 #refcheck=False

'datos_new.resize((3, 5))'

In [ ]:
datos_new.resize((3, 5), refcheck=False)


In [ ]:
datos_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [ ]:
#aqui ya tenemmos incluso la tercer fila, aunque está
#en ceros pero ya esta hecha la tercer linea de datos_new
#ahora queremos llenar esa fila con el dato de
#km_promedio

datos_new[2] = datos_new[0] / (2020 - datos[1])

In [ ]:
datos_new

array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2612.35294118,   196.96551724,  1237.43333333,     0.        ,
         1839.78571429]])

# 5.5 Estadísticas con arrays Numpy

https://numpy.org/doc/1.16/reference/arrays.ndarray.html#calculation

y

https://numpy.org/doc/1.16/reference/routines.statistics.html

y

https://numpy.org/doc/1.16/reference/routines.math.html

In [ ]:
años = np.loadtxt(fname = "/content/carros-años.txt", dtype = int)
km = np.loadtxt(fname = "carros-km.txt")
valor = np.loadtxt(fname = "carros-valor.txt")

In [ ]:
años.shape

(258,)

In [ ]:
#años es de una sola dimension pero para
#hacer calculos estadisticos neccesito  un array de mas de 1 dimension
#concatenaremos, para hacer un array de varias dimensiones
#pero que este organizado

https://numpy.org/doc/1.16/reference/generated/numpy.column_stack.html

In [ ]:
dataset = np.column_stack((años, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0200000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0200000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0200000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0200000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [ ]:
#bien, aqui el metodo colum_stack le pasamos
#los datos q tenemos y que quermos q convierta
# a columna, asi cada lista la convirtio en una sola
#matriz de 3 columnas y varias dimensiones.

In [ ]:
#los valores estan en decimales

In [ ]:
dataset.shape

(258, 3)

## *np.mean()*

Devuelve el promedio de los elementos del array a lo largo del eje especificado.

In [ ]:
#este usa el promedio, vermeos el promedio del datset
np.mean(dataset)

48489.225297157616

In [ ]:
#pero anterioromente hizo una media de todo en conjunto, pero queremos l
#la media de cada dato por separado y esto lo hacemos con
#axis
#asi elegimos si quiere q l media sea de columnas q seria =0
#o de filas que seria =1

#en este caso lo haremos por columnas
np.mean(dataset, axis = 0)

array([ 2007.74806202, 44499.41472868, 98960.51310078])

In [ ]:
#ahora por filas, uqneu no tiene sentio en este caso pero veamos
np.mean(dataset, axis = 1)

array([44830.54666667, 37954.98      , 37315.05333333, 42189.69      ,
       40125.03333333, 36745.91      , 19488.4       , 63972.81333333,
       73974.42333333, 38851.83      , 28836.19666667, 27992.84333333,
       68168.99666667, 18401.12666667, 56984.80666667, 59177.8       ,
       36526.53      , 30190.79666667, 33932.89666667, 39638.76666667,
       69780.79333333, 32194.8       , 77867.61333333, 76878.21666667,
       41205.40333333, 24462.36666667, 34386.25      , 35817.61333333,
       39298.42333333, 72268.23333333, 34289.06666667, 41477.39333333,
       26365.56333333, 33918.13333333, 50905.01      , 54959.84      ,
       17875.53      , 41767.29      , 25768.39333333, 34876.51333333,
       54475.06333333, 59333.43      , 29553.78      , 75040.79666667,
       39882.24333333, 22655.23333333, 52057.21666667, 31725.88333333,
       22240.36666667, 69567.49666667, 78571.96333333, 61600.27666667,
       69114.54333333, 58791.90333333, 31242.99666667, 51282.34333333,
      

In [ ]:
#lo haremos con particion, todas las lineas con solo la primer columna
np.mean(dataset[::, 1])

44499.41472868217

In [ ]:
np.mean(dataset[::, 2])

98960.51310077519

## *np.std()*

Devuelve la desviación estándar de los elementos del array a lo largo del eje especificado.

In [ ]:
'''
La desviación estándar es una medida de dispersión que indica
cuánto se alejan los valores de una muestra o una población
respecto a su media. En otras palabras, mide el promedio de las
diferencias entre los valores individuales y la media del
conjunto de datos. Una desviación estándar baja significa
que los valores tienden a estar cerca de la media, mientras que
una desviación estándar alta indica que los valores están más
dispersos.
'''

In [ ]:
np.std(dataset[::, 2])

29754.101150388564

## *ndarray.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [ ]:
#sumaremos de forma vertical, cada columna puesto
#q representan informcion del mismo vehículo

#esto nos mostrara la suma independient de cada columna
dataset.sum(axis = 0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [ ]:
#otra forma de sumar es con particones
#dataset[lineas, columnas]

dataset[::, 1].sum()


11480849.0

## *np.sum()*

Devuelve la suma de los elementos del array a lo largo del eje especificado.

In [ ]:
np.sum(dataset, axis = 0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [ ]:
np.sum(dataset[::, 2])

25531812.38

Ahora como preambulo del siguiente curso, convertireos el dataset a un DataFrame, importamos pandas, y generamos el dataframe en una variable df q tomara como datos el dataset  le especifico que quiero q lo ponga en columnas, con sus nombres.

Luego genero una variabl resultado q agrupara el df por años, y calculara y mostrara la media del km y el valor segun l agrupación, para finalizar llamando a imprimir a la variable resultado

In [ ]:
import pandas as pd

df = pd.DataFrame(data = dataset, columns=["años", "km", "valor"])
result = df.groupby('años').mean()
print(result)



                  km          valor
años                               
1990.0  72083.666667   96116.206667
1991.0  47036.444444   93420.658889
1992.0  51283.000000   90670.667500
1993.0  55384.250000   93357.635000
1994.0  70260.777778   96623.326667
1995.0  71289.714286   86117.702857
1996.0  50926.100000   98619.528000
1997.0  71897.000000   96852.883333
1998.0  71828.000000   97801.913333
1999.0  39075.500000   98675.220000
2000.0  98921.000000  112101.906667
2001.0  69583.750000  105120.757500
2002.0  59268.545455   89327.512727
2003.0  56926.571429  111672.687143
2004.0  62735.800000   82253.320000
2005.0  58052.500000  117836.888333
2006.0  45569.750000   91200.577500
2007.0  59986.750000  101135.170000
2008.0  61647.833333  103123.380000
2009.0  48694.000000  110470.614286
2010.0  79227.333333   98001.035000
2011.0  53031.000000  106613.244000
2012.0  40817.500000   89212.192500
2013.0  39021.777778  105672.001111
2014.0  57461.500000   87228.613333
2015.0  61032.125000  103795